Initial develop tree.

diff --git a/install-files/optirun b/install-files/optirun
--- a/install-files/optirun
+++ b/install-files/optirun
@@ -59,6 +59,11 @@ Start an application which may use the nVidia graphics card
     from VirtualGL to file LOG. If LOG is empty, messages will be printed to
     standard output
 
+  --vgl-options=OPTIONS
+  --vgl-options OPTIONS
+    These options are passed to vglrun. Use --debug-log=LOG --vgl-options +tr
+    to generate a verbose debug log (useful if programs are segfaulting)
+
   --help
     Prints this help message
 EOF
@@ -73,6 +78,8 @@ msg() {
 # only set VGL_LOG to empty if the variable was not defined, this allows the
 # user to set VGL_LOG= to get default behavior: write to stderr
 : "${VGL_LOG:=/dev/null}"
+
+vgl_options=
 
 while :; do
     case "$1" in
@@ -134,6 +141,14 @@ while :; do
             VGL_LOG="${1#--debug-log=}"
         fi
         ;;
+      --vgl-options=*|--vgl-options)
+        if [[ $1 == --vgl-options ]]; then
+            shift 1
+            vgl_options="$1"
+        else
+            vgl_options="${1#--vgl-options=}"
+        fi
+        ;;
       --)
         # commonly found in parameters, usage: optirun -- -not -recognised -as -param
         shift
@@ -172,6 +187,26 @@ show_msg() {
     fi
 }
 
+# Sends a "I'm alive and want to use X" message to the daemon. Return values:
+# 0 - the message was succesfully sent
+# 1 - the message could not be sent because the FIFO was unavailable
+needs_x() {
+    # XXX: a better way to check if the daemon is running
+    if [ ! -e "$BUMBLEBEE_FIFO" ]; then
+        msg "The Bumblebee daemon has not been started. To start the daemon, run:"
+        # XXX: distro-dependant command
+        msg "    sudo /etc/init.d/bumblebee start"
+        return 1
+    fi
+    if [ ! -w "$BUMBLEBEE_FIFO" ]; then
+        msg "You have no permission to start the Bumblebee X server. Add"
+        msg "yourself to the '$BUMBLEBEE_GROUP' group."
+        return 1
+    fi
+
+    echo start > "$BUMBLEBEE_FIFO"
+}
+
 # Ensures that the X server can be used. Return values:
 # 0 - the X server is available
 # 1 - the X server is unavailable
@@ -186,34 +221,25 @@ optirun_ready() {
             msg "You're already member of the '$BUMBLEBEE_GROUP' group, but"
             msg "need to re-login to apply these changes.."
         else
+            [[ -n "$SUDO_OPTS" ]] && SUDO_CMD="sudo $SUDO_OPTS" || SUDO_CMD="sudo" 
             msg "You've no permission to start the Bumblebee X server. Add"
             msg "yourself to the '$BUMBLEBEE_GROUP' group by running:"
-            msg "    sudo usermod -a -G $BUMBLEBEE_GROUP $(id -u -n)"
+            msg "    $SUDO_CMD usermod $USERMOD_OPTS $BUMBLEBEE_GROUP $(id -u -n)"
         fi
         return 2
     fi
 
     xserver_available "$PIDFILE" "$X_DAEMON" "$X_DAEMON_ARGS" > /dev/null
     case $? in
-      0) # X is started and available
+      [05]) # started or started, but not ready
+        # always send the start command even if the X server is available, this
+        # makes the daemon aware that a client still wants to use a X server
+        # even if a shutdown process was initiated
+        needs_x || return 1
         return 0
         ;;
-      5) # started but not ready
-        ;;
       [12]) # Not started yet
-        # XXX: a better way to check if the daemon is running
-        if [ ! -e "$BUMBLEBEE_FIFO" ]; then
-            msg "The Bumblebee daemon has not been started. To start the daemon, run:"
-            # XXX: distro-dependant command
-            msg "    sudo /etc/init.d/bumblebee start"
-            return 1
-        fi
-        if [ ! -w "$BUMBLEBEE_FIFO" ]; then
-            msg "You have no permission to start the Bumblebee X server. Add"
-            msg "yourself to the '$BUMBLEBEE_GROUP' group."
-            return 1
-        fi
-        echo start > "$BUMBLEBEE_FIFO"
+        needs_x || return 1
         ;;
       3) # xserver / driver crash
         return 1
@@ -259,7 +285,8 @@ optirun_launcher() {
     # export settings from configuration file
     export VGL_LOG
     export VGL_VERBOSE
-    vglrun -c "$VGL_COMPRESS" -d "$VGL_DISPLAY" -ld "$VGL_DRIVER" -- "$@"
+    vglrun -c "$VGL_COMPRESS" -d "$VGL_DISPLAY" -ld "$VGL_DRIVER" \
+        $vgl_options -- "$@"
 
     # notify the daemon that we are done
     echo stop > "$BUMBLEBEE_FIFO"
